{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.wayland.windowManager.niri;
in {
  options.wayland.windowManager.niri = {
    enable = lib.mkEnableOption "niri";

    package = lib.mkPackageOption pkgs "niri" {
      nullable = true;
      extraDescription = ''
        Set to `null` to not add any niri package to your path.
      '';
    };

    systemd = {
      enable =
        lib.mkEnableOption "systemd"
        // {
          default = true;
          description = ''
            Whether to install niri's systemd units from the package, used by niri-session.
          '';
        };

      variables = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = ''
          Environment variables to be imported in the systemd and D-Bus user environment.
        '';
      };
    };

    xwaylandSatellitePackage = lib.mkPackageOption pkgs "xwayland-satellite" {
      nullable = true;
      extraDescription = ''
        With `xwayland-satellite` in `$PATH`, niri can automatically start XWayland when needed.
      '';
    };

    portalPackage = lib.mkPackageOption pkgs "xdg-desktop-portal-gnome" {
      nullable = true;
      extraDescription = ''
        The portal implementation to use with niri.
      '';
    };

    checkConfig = lib.mkOption {
      type = lib.types.bool;
      default = cfg.package != null;
      defaultText = lib.literalExpression "wayland.windowManager.niri.package != null";
      description = "If enabled and package is not null, validates the generated config file.";
    };

    settings = lib.mkOption {
      type = with lib.types; let
        valueType =
          nullOr (oneOf [
            bool
            int
            float
            str
            (attrsOf valueType)
            (listOf valueType)
          ])
          // {
            description = "KDL value";
          };
      in
        attrsOf valueType;
      default = {};
      description = ''
        Configuration added to `$XDG_CONFIG_HOME/niri/config.kdl`.
      '';
    };

    extraConfigEarly = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra configuration lines added before generated niri settings.";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra configuration lines added after generated niri settings.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      (lib.hm.assertions.assertPlatform "wayland.windowManager.niri" pkgs lib.platforms.linux)
      {
        assertion = cfg.systemd.enable -> cfg.package != null;
        message = "wayland.windowManager.niri.systemd.enable requires a non-null package";
      }
      {
        assertion = cfg.checkConfig -> cfg.package != null;
        message = "wayland.windowManager.niri.checkConfig requires a non-null package";
      }
    ];

    home.packages = lib.concatLists [
      (lib.optional (cfg.package != null) cfg.package)
      (lib.optional (cfg.xwaylandSatellitePackage != null) cfg.xwaylandSatellitePackage)
    ];

    systemd.user.packages = lib.optional cfg.systemd.enable cfg.package;

    xdg.portal = lib.mkIf (cfg.portalPackage != null) {
      enable = true;
      extraPortals = [cfg.portalPackage];
      configPackages = lib.optional (cfg.package != null) cfg.package;
    };

    xdg.configFile."niri/config.kdl" = let
      toKDL = lib.hm.generators.toKDL {
        escapeBackslashes = true;
        escapeTabs = true;
      };
      settings = lib.trim (toKDL cfg.settings);
      configLines = lib.concatStringsSep "\n" (
        lib.filter (line: line != "") [
          cfg.extraConfigEarly
          settings
          cfg.extraConfig
        ]
      );
    in
      lib.mkIf (configLines != "") {
        source = pkgs.writeTextFile {
          name = "niri-config.kdl";
          text = ''
            // Automatically generated by home-manager from `wayland.windowManager.niri`
            ${configLines}
          '';
          checkPhase = lib.optionalString cfg.checkConfig ''
            ${lib.getExe cfg.package} validate --config "$target"
          '';
        };
      };
  };
}
